INSERT INTO Размеры values (20)
INSERT INTO Размеры values (30)
INSERT INTO Размеры values (40)
INSERT INTO Размеры values (50)
INSERT INTO Размеры values (60)

INSERT INTO Полнота values (11)
INSERT INTO Полнота values (22)
INSERT INTO Полнота values (33)
INSERT INTO Полнота values (44)
INSERT INTO Полнота values (55)

INSERT INTO Рост values (110)
INSERT INTO Рост values (120)
INSERT INTO Рост values (133)
INSERT INTO Рост values (144)
INSERT INTO Рост values (155)

INSERT INTO Цвета values (0123)
INSERT INTO Цвета values (2445)
INSERT INTO Цвета values (3311)
INSERT INTO Цвета values (4213)
INSERT INTO Цвета values (5456)

INSERT INTO Изделия values ('Куртка')
INSERT INTO Изделия values ('Шапка')
INSERT INTO Изделия values ('Майка')
INSERT INTO Изделия values ('Кофта')
INSERT INTO Изделия values ('Штаны')

INSERT INTO Модели_изделия values (1, 'летняя')
INSERT INTO Модели_изделия values (1, 'зимнняя')
INSERT INTO Модели_изделия values (2, 'утепленная')
INSERT INTO Модели_изделия values (2, 'легкая')
INSERT INTO Модели_изделия values (3, 'летняя')
INSERT INTO Модели_изделия values (3, '0123-Р')
INSERT INTO Модели_изделия values (4, 'летняя')
INSERT INTO Модели_изделия values (4, 'зимнняя')
INSERT INTO Модели_изделия values (5, 'утепленные')
INSERT INTO Модели_изделия values (5, 'летние')

INSERT INTO Маршрутные_листы values (1, 1, 1, 1, 1, 40123)
INSERT INTO Маршрутные_листы values (1, 2, 2, 2, 2, 40124)
INSERT INTO Маршрутные_листы values (2, 1, 1, 1, 1, 40125)
INSERT INTO Маршрутные_листы values (2, 3, 4, 5, 3, 40126)
INSERT INTO Маршрутные_листы values (3, 4, 4, 4, 5, 40127)
INSERT INTO Маршрутные_листы values (3, 3, 3, 3, 3, 40128)